.TH STRERROR "1" "February 2013" "strerror 0.1.0" "User Commands"
.SH NAME
strerror \- manual page for strerror 0.1.0
.SH SYNOPSIS
.B strerror
[\fIOPTION\fR]... \fIERROR\fR
.SH DESCRIPTION
strerror 0.1.0
.PP
Parse ERROR (an errno code or an errno literal) and print its expansion.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help and exit
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version and exit
.SH "EXAMPLES"
  % strerror 11
  11	EAGAIN	Resource temporarily unavailable

  % strerror ERANGE
  34	ERANGE	Numerical result out of range

  % strerror 15 EBUSY
  15	ENOTBLK	Block device required
  16	EBUSY	Device or resource busy
.PP
